# Generated by Django 4.2.23 on 2025-07-05 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0003_alter_membership_role1_alter_membership_role2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='submissions/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=255)),
                ('co_authors', models.ManyToManyField(related_name='co_authored_submissions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='membership.membership')),
            ],
            options={
                'ordering': ['-submission_date'],
                'unique_together': {('membership', 'paper_title')},
            },
        ),
    ]
