# Generated by Django 4.2.23 on 2025-08-01 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='co_authors',
        ),
        migrations.AddField(
            model_name='submissions',
            name='co_author1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coauthor1_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissions',
            name='co_author2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coauthor2_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissions',
            name='co_author3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coauthor3_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
