# Generated by Django 4.2.23 on 2025-08-05 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role1', models.CharField(choices=[('Author', 'Author'), ('Reviewer', 'Reviewer'), ('Chair', 'Chair'), ('N/A', 'N/A')], default='Author', max_length=50)),
                ('role2', models.CharField(choices=[('Author', 'Author'), ('Reviewer', 'Reviewer'), ('Chair', 'Chair'), ('N/A', 'N/A')], default='N/A', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='conference.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'conference')},
            },
        ),
    ]
