# Generated by Django 5.2.3 on 2025-06-28 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role1', models.CharField(choices=[('Author', 'Author'), ('Reviewer', 'Reviewer'), ('Chair', 'Chair')], default='Author', max_length=50)),
                ('role2', models.CharField(choices=[('Author', 'Author'), ('Reviewer', 'Reviewer'), ('Chair', 'Chair')], default='Reviewer', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=50)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='conference.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'conference')},
            },
        ),
    ]
