# Generated by Django 5.2.3 on 2025-06-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role1',
            field=models.CharField(choices=[('Author', 'Author'), ('Reviewer', 'Reviewer'), ('Chair', 'Chair'), ('N/A', 'N/A')], default='Author', max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role2',
            field=models.CharField(choices=[('Author', 'Author'), ('Reviewer', 'Reviewer'), ('Chair', 'Chair'), ('N/A', 'N/A')], default='N/A', max_length=50),
        ),
    ]
