# Generated by Django 4.2.23 on 2025-07-05 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0003_alter_membership_role1_alter_membership_role2'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('REVISE', 'Needs Revision'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='membership.membership')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='submissions.submissions')),
            ],
            options={
                'unique_together': {('membership', 'submission')},
            },
        ),
    ]
