# Generated by Django 4.2.23 on 2025-08-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('REVISE', 'Needs Revision')], max_length=10, null=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_assigned', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submissions')),
            ],
            options={
                'ordering': ['-date_reviewed', '-date_assigned'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
    ]
