# Generated by Django 4.2.23 on 2025-08-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submissions_co_author1_and_more'),
        ('review', '0002_alter_review_unique_together_review_date_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submissions'),
        ),
    ]
