name: Deploy to EC2 via AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
        role-duration-seconds: 1200
      
    - name: Deploy to EC2 using AWS SSM
      run: |
        # Send deployment command to EC2 via AWS Systems Manager
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "if [ ! -d /srv/iatm/.git ]; then",
            "  cd /srv",
            "  git clone https://github.com/Prakhar6/IATM-Conference-Management-Tool.git iatm",
            "fi",
            "cd /srv/iatm",
            "git pull origin main",
            "docker-compose down",
            "docker-compose up -d --build",
            "echo \"Deployment completed successfully!\"
          ]'
      
    - name: Wait for deployment
      run: |
        # Wait for the command to complete
        sleep 30
        echo "Deployment command sent to EC2 instance"
