name: Deploy to EC2 via AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
        role-duration-seconds: 1200
      
    - name: Deploy to EC2 using AWS SSM
      run: |
        # Send deployment command to EC2 via AWS Systems Manager
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "cd /srv/iatm",
            "git pull origin main",
            "cd \"cmt project\"",
            "pip install -r requirements.txt",
            "python manage.py migrate",
            "python manage.py collectstatic --noinput",
            "cd ..",
            "docker stop iatm-app-1",
            "docker rm iatm-app-1",
            "docker build -t iatm:latest .",
            "docker run -d --name iatm-app-1 -p 8000:8000 iatm:latest",
            "echo \"Deployment completed successfully!\"
          ]'
      
    - name: Wait for deployment
      run: |
        # Wait for the command to complete
        sleep 30
        echo "Deployment command sent to EC2 instance"
