# Generated by Django 4.2.23 on 2025-09-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='conference',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='conference',
            name='slug',
            field=models.SlugField(blank=True, default=True, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
