# Generated by Django 5.2.3 on 2026-03-14 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='blind_review',
            field=models.BooleanField(default=False, help_text='Hide author info from reviewers'),
        ),
        migrations.AddField(
            model_name='conference',
            name='early_bird_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='member_discount_percent',
            field=models.PositiveIntegerField(default=10, help_text='Discount % for IATM members'),
        ),
        migrations.AddField(
            model_name='conference',
            name='review_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for reviewers to submit reviews', null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for paper submissions', null=True),
        ),
        migrations.CreateModel(
            name='RegistrationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='conference.conference')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('conference', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='conference.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conference.registrationtier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
